#!/bin/bash
# Script for EPG grab from WebGrab+Plus  http://www.webgrabplus.com/documentation
set -x

function git_clone()
{
git clone git@github.com:muzena/samdecrypt.git -b libepg
cd samdecrypt
./update-epg-guide <<EOF
EOF
}


git_clone
wait $!
cd ..
wait $!
chmod a+rw -R samdecrypt
wait $!
rm -R samdecrypt
