#!/bin/bash
#set -e
set -x  debug


####################################################################################

#echo "Checking and creating if it need user data file."
#FILE=~/.decrypt_userdata
#if [ -f $FILE ]; then
#   echo "File '$FILE' exists"
#else
#   echo 'usb="sda1"
#tvip="ENTER_YOUR_TV_IP"' > ~/.decrypt_userdata
#fi
echo "Selecting TV ip address and recording devices."
usb=""
tvip=""
path=""
widgetpath=""
#target="/usr/share/samdecrypt/.decrypt_userdata"
#M_OPTS="$PERM,usb=${USER},tvip=${PASSWD},codepage=cp1250,iocharset=utf8"
[ -e /usr/share/samdecrypt/.decrypt_userdata ] && source /usr/share/samdecrypt/.decrypt_userdata
[ -z $usb ] && exit 1
[ -z $tvip ] && exit 1
[ -z $path ] && exit 1
[ -z $widgetpath ] && exit 1

####################################################################################

# choice=$(cat $widgetpath/list.txt
choice1=$widgetpath
choice2=$path

function makewidget_folder()
{ 
if [ "$choice1" ]
  then
     echo "Folder exist"
  else
    echo "Making widget folder"
    mkdir $widgetpath
fi
}

function makedecoding_folder()
{ 
if [ "$choice2" ]
  then
     echo "Folder exist"
  else
    echo "Making decoding folder"
    mkdir $path
fi
}

makewidget_folder



