#!/bin/bash
set -x

conf1="gksu samsettingsgui"
conf2="xterm samconfigure"

echo "Selecting TV ip address and recording devices."
usb=""
tvip=""
path=""
widgetpath=""
sec="20"
#target="/usr/share/samdecrypt/.decrypt_userdata"
#M_OPTS="$PERM,usb=${USER},tvip=${PASSWD},codepage=cp1250,iocharset=utf8"
[ -e /usr/share/samdecrypt/.decrypt_userdata ] && source /usr/share/samdecrypt/.decrypt_userdata
[ -z $usb ] && exit 1
[ -z $tvip ] && exit 1
[ -z $path ] && exit 1
[ -z $widgetpath ] && exit 1

####################################################################################
echo "Testing Samsung TV availability"

if ping -c 1 "$tvip" &> /dev/null
then
  echo "Samsung TV available"
  exit
else
  echo "Samsung TV isn't available IPTV in settings"

  notify-send --app-name="Samdecrypt" --expire-time="6000" --icon="/usr/share/pixmaps/samdecrypt.png" "Samsung TV isn't available, set IPTV in settings"

yad --info \
    --title="Samdecrypt warning" \
    --width=300 \
    --text="Configure Samsung TV IP, if <b>GUI settings</b> failed then use <b>CLI settings</b>" \
    --button="GUI settings:$conf1" \
    --button="CLI settings:$conf2" \
    --button="Close settings:1" \
    --kill-parent="1" \

exit
fi

exit
