#!/bin/bash
#set -e
set -x  debug

####################################################################################
echo "Configure samdecrypt."
sudo dpkg-reconfigure samdecrypt
notify-send --app-name="Samdecrypt" --expire-time="3000" --icon="/usr/share/pixmaps/samdecrypt.png" "Samdecrypt is configured"


echo "Samdecrypt configured"


exit
