#!/bin/bash

set -x

rm guide-test.xml
rm ./pharser/guide.xml
rm ./pharser/libEPG.config
cd wg++
mono WebGrab+Plus.exe "$(pwd)"
wait $!
cd ..
./fix-channel-names
cp guide-test.xml ./pharser/guide.xml
cd pharser
python pharser.py
