#!/bin/bash
# Script for EPG grab from WebGrab+Plus  http://www.webgrabplus.com/documentation
set -x

function fixchannelnames_port()
{
# Nova TV
sed -e 's/"NOVA TV">/"NOVA">/g' guide.xml > guide-test.xml
sed -i 's/>NOVA TV</>NOVA</g' guide-test.xml
# RTL TELEVIZIJA
sed -i 's/"RTL TELEVIZIJA">/"RTL">/g' guide-test.xml
sed -i 's/>RTL TELEVIZIJA</>RTL</g' guide-test.xml
# Doma TV
sed -i 's/"Doma TV">/"Doma">/g' guide-test.xml
sed -i 's/>Doma TV</>Doma</g' guide-test.xml
# RTL TELEVIZIJA
sed -i 's/"Doma TV">/"Doma">/g' guide-test.xml
sed -i 's/>Doma TV</>Doma</g' guide-test.xml
# RTL 2
sed -i 's/"RTL 2">/"RTL2">/g' guide-test.xml
sed -i 's/>RTL 2</>RTL2</g' guide-test.xml
# RTL Plus
sed -i 's/"RTL Plus">/"RTLpl">/g' guide-test.xml
sed -i 's/>RTL Plus</>RTLpl</g' guide-test.xml
# CineStar TV
sed -i 's/"CineStar Action&amp;Thriller">/"CineA">/g' guide-test.xml
sed -i 's/>CineStar Action&amp;Thriller</>CineA</g' guide-test.xml
# CineStar Action&amp;Thriller
sed -i 's/"CineStar TV">/"Cines">/g' guide-test.xml
sed -i 's/>CineStar TV</>Cines</g' guide-test.xml
# TV 1000 Balkan
sed -i 's/"TV 1000 Balkan">/"TV100">/g' guide-test.xml
sed -i 's/>TV 1000 Balkan</>TV100</g' guide-test.xml
# Fox TV
sed -i 's/"Fox TV">/"Fox">/g' guide-test.xml
sed -i 's/>Fox TV</>Fox</g' guide-test.xml
# Fox Life
sed -i 's/"Fox Life">/"FoxLi">/g' guide-test.xml
sed -i 's/>Fox Life</>FoxLi</g' guide-test.xml
# Universal Channel
sed -i 's/"Universal Channel">/"Unive">/g' guide-test.xml
sed -i 's/>Universal Channel</>Unive</g' guide-test.xml
# Discovery Channel
sed -i 's/"Discovery Channel">/"Disco">/g' guide-test.xml
sed -i 's/>Discovery Channel</>Disco</g' guide-test.xml
# National Geographic Channel
sed -i 's/"National Geographic Channel">/"NatGe">/g' guide-test.xml
sed -i 's/>National Geographic Channel</>NatGe</g' guide-test.xml
# Viasat History
sed -i 's/"Viasat History">/"Histo">/g' guide-test.xml
sed -i 's/>Viasat History</>Histo</g' guide-test.xml
# Animal Planet
sed -i 's/"Animal Planet">/"Anima">/g' guide-test.xml
sed -i 's/>Animal Planet</>Anima</g' guide-test.xml
# Viasat Explore
sed -i 's/"Viasat Explore">/"Explo">/g' guide-test.xml
sed -i 's/>Viasat Explore</>Explo</g' guide-test.xml
# Travel Channel
sed -i 's/"Travel Channel">/"TLC">/g' guide-test.xml
sed -i 's/>Travel Channel</>TLC</g' guide-test.xml
# MrežaZG
sed -i 's/"MrežaZG">/"Mreža">/g' guide-test.xml
sed -i 's/>MrežaZG</>Mreža</g' guide-test.xml
# Jabuka TV
sed -i 's/"Jabuka TV">/"Jabuk">/g' guide-test.xml
sed -i 's/>Jabuka TV</>Jabuk</g' guide-test.xml
# Z1
sed -i 's/"Z1">/"Z 1">/g' guide-test.xml
sed -i 's/>Z1</>Z 1</g' guide-test.xml
# 24 SATA TV
sed -i 's/"24 SATA TV">/"24sat">/g' guide-test.xml
sed -i 's/>24 SATA TV</>24sat</g' guide-test.xml
# CNN International Europe
sed -i 's/"CNN International Europe">/"CNN">/g' guide-test.xml
sed -i 's/>CNN International Europe</>CNN</g' guide-test.xml
# Cartoon Network
sed -i 's/"Cartoon Network">/"CN">/g' guide-test.xml
sed -i 's/>Cartoon Network</>CN</g' guide-test.xml
# Nickelodeon
sed -i 's/"Nickelodeon">/"Nicke">/g' guide-test.xml
sed -i 's/>Nickelodeon</>Nicke</g' guide-test.xml
# DISNEY CHANNEL
sed -i 's/"DISNEY CHANNEL">/"Disne">/g' guide-test.xml
sed -i 's/>DISNEY CHANNEL</>Disne</g' guide-test.xml
# Mini TV
sed -i 's/"Mini TV">/"Mini">/g' guide-test.xml
sed -i 's/>Mini TV</>Mini</g' guide-test.xml
# RTL Kockica
sed -i 's/"RTL Kockica">/"RTLko">/g' guide-test.xml
sed -i 's/>RTL Kockica</>RTLko</g' guide-test.xml
# Sportska televizija
sed -i 's/"Sportska televizija">/"SPTV">/g' guide-test.xml
sed -i 's/>Sportska televizija</>SPTV</g' guide-test.xml
# Eurosport
sed -i 's/"Eurosport">/"Euro1">/g' guide-test.xml
sed -i 's/>Eurosport</>Euro1</g' guide-test.xml
# Eurosport 2
sed -i 's/"Eurosport 2">/"Euro2">/g' guide-test.xml
sed -i 's/>Eurosport 2</>Euro2</g' guide-test.xml
# SK 1
sed -i 's/"SK 1">/"SK1">/g' guide-test.xml
sed -i 's/>SK 1</>SK1</g' guide-test.xml
# SK 3
sed -i 's/"SK 3">/"SK3">/g' guide-test.xml
sed -i 's/>SK 3</>SK3</g' guide-test.xml
# MTV Hrvatska
sed -i 's/"MTV Hrvatska">/"MTV">/g' guide-test.xml
sed -i 's/>MTV Hrvatska</>MTV</g' guide-test.xml
# VH1 Europe
sed -i 's/"VH1 Europe">/"VH1">/g' guide-test.xml
sed -i 's/>VH1 Europe</>VH1</g' guide-test.xml
# CMC
sed -i 's/"CMC">/"C M C">/g' guide-test.xml
sed -i 's/>CMC</>C M C</g' guide-test.xml
# N1
sed -i 's/"N1">/"N 1">/g' guide-test.xml
sed -i 's/>N1</>N 1</g' guide-test.xml
 <<EOF
EOF
}
function fixchannelnames_bnet()
{
# Nova TV
sed -e 's/"NOVA TV">/"NOVA">/g' guide.xml > guide-test.xml
sed -i 's/>NOVA TV</>NOVA</g' guide-test.xml
# HRT 1
sed -i 's/"HTV 1">/"HRT 1">/g' guide-test.xml
sed -i 's/>HTV 1</>HRT 1</g' guide-test.xml
# HRT 2
sed -i 's/"HTV 2">/"HRT 2">/g' guide-test.xml
sed -i 's/>HTV 2</>HRT 2</g' guide-test.xml
# HRT 3
sed -i 's/"HTV 3">/"HRT 3">/g' guide-test.xml
sed -i 's/>HTV 3</>HRT 3</g' guide-test.xml
# HRT 4
sed -i 's/"HTV 4">/"HRT 4">/g' guide-test.xml
sed -i 's/>HTV 4</>HRT 4</g' guide-test.xml
# RTL TELEVIZIJA
sed -i 's/"RTL TELEVIZIJA">/"RTL">/g' guide-test.xml
sed -i 's/>RTL TELEVIZIJA</>RTL</g' guide-test.xml
# Doma TV
sed -i 's/"Doma TV">/"Doma">/g' guide-test.xml
sed -i 's/>Doma TV</>Doma</g' guide-test.xml
# RTL TELEVIZIJA
sed -i 's/"DOMA TV">/"Doma">/g' guide-test.xml
sed -i 's/>DOMA TV</>Doma</g' guide-test.xml
# RTL 2
#sed -i 's/"RTL2">/"RTL2">/g' guide-test.xml
#sed -i 's/>RTL2</>RTL2</g' guide-test.xml
# RTL Plus
sed -i 's/"RTL PLUS">/"RTLpl">/g' guide-test.xml
sed -i 's/>RTL PLUS</>RTLpl</g' guide-test.xml
# CineStar TV
sed -i 's/"CINESTAR ACTION &amp; THRILLER">/"CineA">/g' guide-test.xml
sed -i 's/>CINESTAR ACTION &amp; THRILLER</>CineA</g' guide-test.xml
# CineStar Action&amp;Thriller
sed -i 's/"CINESTAR TV">/"Cines">/g' guide-test.xml
sed -i 's/>CINESTAR TV</>Cines</g' guide-test.xml
# TV 1000 Balkan
sed -i 's/"VIASAT TV1000">/"TV100">/g' guide-test.xml
sed -i 's/>VIASAT TV1000</>TV100</g' guide-test.xml
# Fox TV
sed -i 's/"FOX">/"Fox">/g' guide-test.xml
sed -i 's/>FOX</>Fox</g' guide-test.xml
# Fox Life
sed -i 's/"FOX LIFE">/"FoxLi">/g' guide-test.xml
sed -i 's/>FOX LIFE</>FoxLi</g' guide-test.xml
# Universal Channel
sed -i 's/"UNIVERSAL CHANNEL">/"Unive">/g' guide-test.xml
sed -i 's/>UNIVERSAL CHANNEL</>Unive</g' guide-test.xml
# Discovery Channel
sed -i 's/"DISCOVERY CHANNEL">/"Disco">/g' guide-test.xml
sed -i 's/>DISCOVERY CHANNEL</>Disco</g' guide-test.xml
# National Geographic Channel
sed -i 's/"NATIONAL GEOGRAPHIC">/"NatGe">/g' guide-test.xml
sed -i 's/>NATIONAL GEOGRAPHIC</>NatGe</g' guide-test.xml
# Viasat History
sed -i 's/"VIASAT HISTORY">/"Histo">/g' guide-test.xml
sed -i 's/>VIASAT HISTORY</>Histo</g' guide-test.xml
# Animal Planet
sed -i 's/"ANIMAL PLANET">/"Anima">/g' guide-test.xml
sed -i 's/>ANIMAL PLANET</>Anima</g' guide-test.xml
# Viasat Explore
sed -i 's/"VIASAT EXPLORER">/"Explo">/g' guide-test.xml
sed -i 's/>VIASAT EXPLORER</>Explo</g' guide-test.xml
# Travel Channel
#sed -i 's/"TLC">/"TLC">/g' guide-test.xml
#sed -i 's/>TLC</>TLC</g' guide-test.xml
# MrežaZG
sed -i 's/"MREŽAZG">/"Mreža">/g' guide-test.xml
sed -i 's/>MREŽAZG</>Mreža</g' guide-test.xml
# Jabuka TV
sed -i 's/"Jabuka TV">/"Jabuk">/g' guide-test.xml
sed -i 's/>Jabuka TV</>Jabuk</g' guide-test.xml
# Z1
sed -i 's/"Z1">/"Z 1">/g' guide-test.xml
sed -i 's/>Z1</>Z 1</g' guide-test.xml
# 24 SATA TV
sed -i 's/"24 SATA TV">/"24sat">/g' guide-test.xml
sed -i 's/>24 SATA TV</>24sat</g' guide-test.xml
# CNN International Europe
sed -i 's/"CNN">/"CNN">/g' guide-test.xml
sed -i 's/>CNN</>CNN</g' guide-test.xml
# Cartoon Network
sed -i 's/"CARTOON NETWORK">/"CN">/g' guide-test.xml
sed -i 's/>CARTOON NETWORK</>CN</g' guide-test.xml
# Nickelodeon
sed -i 's/"NICKELODEON">/"Nicke">/g' guide-test.xml
sed -i 's/>NICKELODEON</>Nicke</g' guide-test.xml
# DISNEY CHANNEL
sed -i 's/"DISNEY CHANNEL">/"Disne">/g' guide-test.xml
sed -i 's/>DISNEY CHANNEL</>Disne</g' guide-test.xml
# Mini TV
sed -i 's/"MINI TV">/"Mini">/g' guide-test.xml
sed -i 's/>MINI TV</>Mini</g' guide-test.xml
# RTL Kockica
sed -i 's/"RTL KOCKICA">/"RTLko">/g' guide-test.xml
sed -i 's/>RTL KOCKICA</>RTLko</g' guide-test.xml
# Sportska televizija
sed -i 's/"SPORTSKA TV">/"SPTV">/g' guide-test.xml
sed -i 's/>SPORTSKA TV</>SPTV</g' guide-test.xml
# Eurosport
sed -i 's/"EUROSPORT">/"Euro1">/g' guide-test.xml
sed -i 's/>EUROSPORT</>Euro1</g' guide-test.xml
# Eurosport 2
sed -i 's/"EUROSPORT 2">/"Euro2">/g' guide-test.xml
sed -i 's/>EUROSPORT 2</>Euro2</g' guide-test.xml
# SK 1
sed -i 's/"SK 1">/"SK1">/g' guide-test.xml
sed -i 's/>SK 1</>SK1</g' guide-test.xml
# SK 3
sed -i 's/"SK 3">/"SK3">/g' guide-test.xml
sed -i 's/>SK 3</>SK3</g' guide-test.xml
# MTV Hrvatska
sed -i 's/"MTV">/"MTV">/g' guide-test.xml
sed -i 's/>MTV</>MTV</g' guide-test.xml
# VH1 Europe
sed -i 's/"VH1">/"VH1">/g' guide-test.xml
sed -i 's/>VH1</>VH1</g' guide-test.xml
# CMC
sed -i 's/"CROATIAN MUSIC CHANNEL">/"C M C">/g' guide-test.xml
sed -i 's/>CROATIAN MUSIC CHANNEL</>C M C</g' guide-test.xml
# N1
sed -i 's/"N1">/"N 1">/g' guide-test.xml
sed -i 's/>N1</>N 1</g' guide-test.xml
######################################################
# FOX tv online test tv
sed -i 's/"Fox TV">/"FOX sr">/g' guide-test.xml
sed -i 's/>Fox TV</>FOX sr</g' guide-test.xml
# B92 tv online test tv
sed -i 's/"B92">/"B92 HD">/g' guide-test.xml
sed -i 's/>B92</>B92 HD</g' guide-test.xml
# FOX Life online test tv
sed -i 's/"Fox Life">/"FOX Life sr">/g' guide-test.xml
sed -i 's/>Fox Life</>FOX Life sr</g' guide-test.xml
# MTV online test tv
sed -i 's/"MTV Hrvatska">/"MTV Adria sr">/g' guide-test.xml
sed -i 's/>MTV Hrvatska</>MTV Adria sr</g' guide-test.xml
# Viasat Nature online test tv
sed -i 's/"Viasat Nature">/"VIASAT NATURE sr">/g' guide-test.xml
sed -i 's/>Viasat Nature</>VIASAT NATURE sr</g' guide-test.xml
# Pink online test tv
sed -i 's/"PINK">/"PINK sr">/g' guide-test.xml
sed -i 's/>PINK</>PINK sr</g' guide-test.xml
# Vh1 online test tv
sed -i 's/"VH1 Europe">/"VH1 sr">/g' guide-test.xml
sed -i 's/>VH1 Europe</>VH1 sr</g' guide-test.xml




# ESKA tv online test tv
sed -i 's/"Eska TV">/"Eska 2">/g' guide-test.xml
sed -i 's/>Eska TV</>Eska 2</g' guide-test.xml
# Correct hr language header
sed -i 's/lang="pl/lang="hr/g' guide-test.xml
 <<EOF
EOF
}
function update_grabber()
{
rm ./pharser/libEPG.config
rm ./wg++/WebGrab++.config.xml
# Channels from Bnet
cp ./wg++/WebGrab++.config-bnet.xml ./wg++/WebGrab++.config.xml
# Channels from Port
#cp ./wg++/WebGrab++.config-port.xml ./wg++/WebGrab++.config.xml
cd wg++
mono WebGrab+Plus.exe "$(pwd)"
wait $!
cd ..
fixchannelnames_bnet
#fixchannelnames_port
wait $!
cp guide-test.xml ./pharser/guide.xml
rm guide-test.xml
cd pharser
python pharser.py
wait $!
rm guide.xml
cd .. <<EOF
EOF
}
function git_clone()
{
git clone https://github.com/muzena/samdecrypt.git
cd samdecrypt
git status
git checkout libepg
git status
cd .. <<EOF
EOF
}
function upload_togit()
{
#cd samdecrypt
git add -A
git commit -m update
git push origin libepg
cd .. <<EOF
EOF
}




update_grabber
wait $!
#git_clone
#wait $!
#rm ./pharser/libEPG.config
#wait $!
#cp ./pharser/libEPG.config ./samdecrypt/pharser/libEPG.config
#wait $!
upload_togit
wait $!
