#!/bin/bash
#set -e
set -x  #debug

#Script for restaritng Samsung TV

####################################################################################

#echo "Checking and creating if it need user data file."
#FILE=~/.decrypt_userdata
#if [ -f $FILE ]; then
#   echo "File '$FILE' exists"
#else
#   echo 'usb="sda1"
#tvip="ENTER_YOUR_TV_IP"' > ~/.decrypt_userdata
#fi
echo "Selecting TV ip adress and recording devices."
usb=""
tvip=""
path=""
sec="20"
#target="/usr/share/samdecrypt/.decrypt_userdata"
#M_OPTS="$PERM,usb=${USER},tvip=${PASSWD},codepage=cp1250,iocharset=utf8"
[ -e /usr/share/samdecrypt/.decrypt_userdata ] && source /usr/share/samdecrypt/.decrypt_userdata
[ -z $usb ] && exit 1
[ -z $tvip ] && exit 1
[ -z $path ] && exit 1
####################################################################################
webpath='http://$tvip:1080/cgi-bin/test.cgi'
conf1=(/usr/share/samdecrypt/web-interface-startstop)
#conf1="xdg-open $webpath"
conf2=(/usr/share/samdecrypt/web-interface-shel)
conf3=(/usr/share/samdecrypt/web-interface-filemanager)
conf4="/usr/share/samdecrypt/reboot-tv"


yad --info \
    --title="Samdecrypt warning" \
    --width=300 \
    --text="Select web interface access.
    \nFor <b>Web shell</b> name is: <b>user</b>: password is: <b>pass</b>" \
    --button="Start stop scripts:$conf1" \
    --button="Web shell:$conf2" \
    --button="File manager:$conf3" \
    --button="Close settings:1" \
    --kill-parent="1" \



