#!/bin/bash
#set -e
set -x  debug

 

####################################################################################

#echo "Checking and creating if it need user data file."
#FILE=~/.decrypt_userdata
#if [ -f $FILE ]; then
#   echo "File '$FILE' exists"
#else
#   echo 'usb="sda1"
#tvip="ENTER_YOUR_TV_IP"' > ~/.decrypt_userdata
#fi
echo "Selecting TV ip address and recording devices."
usb=""
tvip=""
path=""
widgetpath=""
#target="/usr/share/samdecrypt/.decrypt_userdata"
#M_OPTS="$PERM,usb=${USER},tvip=${PASSWD},codepage=cp1250,iocharset=utf8"
[ -e /usr/share/samdecrypt/.decrypt_userdata ] && source /usr/share/samdecrypt/.decrypt_userdata
[ -z $usb ] && exit 1
[ -z $tvip ] && exit 1
[ -z $path ] && exit 1
[ -z $widgetpath ] && exit 1

####################################################################################
#echo "Make widget directory if doesn't exist."
#mkdir $widgetpath

#widgetfolder="xdg-open $widgetpath"

conf1="/usr/share/samdecrypt/backup-widget.sh"
conf2="/usr/share/samdecrypt/download-hub-widgets.sh"
conf3="/usr/share/samdecrypt/reboot-tv"

yad --info \
    --title="Widgets" \
    --width=300 \
    --text="Backup widget added manual by <b>user</b>, or installed by <b>widget hub</b>
    For more info visit:
    http://wiki.samygo.tv/index.php5/How_To_Set_Your_Country_Code_In_Smart_Hub" \
    --button="Backup user widgets:$conf1" \
    --button="Backup hub widgets:$conf2" \
    --button="Reboot TV:$conf3" \
    --button="Close:1" \
    --kill-parent="1" \

exit



