#!/bin/bash

SAM_RUN=`yad \
           --class="Samdecrypt" \
           --name="Samdecrypt" \
           --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" \
           --icons \
           --item-width="182" \
           --read-dir="/usr/share/samdecrypt/desktopfiles" \
           --width="400" \
           --height="400" \
           --title="Samdecrypt" \
           --text="\n<b>Double click</b> an item to perform an action:" \
           --button="Close:1"` \
